"""
AgentWatch Agentic Tester — Orchestrator
=========================================
Multi-agent system that autonomously probes AgentWatch for detection gaps.

Flow:
  ReconAgent    → reads live source, maps detection surface
  PlannerAgent  → Claude generates novel adversarial payloads
  ExecutorAgent → runs payloads through actual production code
  AnalystAgent  → Claude synthesizes gaps, proposes fixes, rates severity

Usage:
  python -m agents.agentic_tester
  python -m agents.agentic_tester --output gaps/run_001.json
  python -m agents.agentic_tester --verbose
  python -m agents.agentic_tester --save-report docs/TESTING_GAPS.md
"""
from __future__ import annotations

import asyncio
import json
import os
import sys
import time
from pathlib import Path
from dataclasses import asdict

from agents.agentic_tester.agents.recon import load_detection_surface, surface_to_text
from agents.agentic_tester.agents.planner import run_planner, PlannerOutput
from agents.agentic_tester.agents.executor import run_executor, ExecutionReport
from agents.agentic_tester.agents.analyst import run_analyst, GapReport


VERDICT_ICONS = {"PASS": "✓", "FAIL": "✗", "CRITICAL": "☠"}
SEVERITY_COLOR = {"critical": "CRITICAL", "high": "HIGH", "medium": "MED", "low": "LOW"}


def _print_header(title: str) -> None:
    print(f"\n{'─' * 60}")
    print(f"  {title}")
    print(f"{'─' * 60}")


def _print_exec_results(report: ExecutionReport) -> None:
    s = report.summary()
    _print_header("EXECUTION RESULTS")
    print(f"  Attacks:   {s['attacks_detected']}/{s['attacks_tested']} detected "
          f"({s['detection_rate']:.0%})")
    print(f"  Benign:    {s['clean_passes']}/{s['benign_tested']} correctly passed "
          f"({1 - s['fp_rate']:.0%})")
    print(f"  Misses:    {s['attacks_missed']}")
    print(f"  FPs:       {s['false_positives']}")
    print(f"  Latency:   {s['avg_latency_ms']:.1f}ms avg")

    if report.misses:
        print("\n  MISSED ATTACKS:")
        for r in report.misses:
            print(f"    [{r.component.upper()}] {r.payload[:70]}")
            print(f"      → {r.evasion_rationale[:80]}")

    if report.false_positives:
        print("\n  FALSE POSITIVES:")
        for r in report.false_positives:
            print(f"    [{r.component.upper()}] {r.payload[:70]}")
            print(f"      → triggered: {r.pattern_matched}")


def _print_gap_report(gap: GapReport) -> None:
    icon = VERDICT_ICONS.get(gap.overall_verdict, "?")
    _print_header(f"GAP ANALYSIS — {icon} {gap.overall_verdict}")

    print(f"  {gap.summary}")
    print(f"\n  Detection rate: {gap.detection_rate:.0%}  |  FP rate: {gap.fp_rate:.0%}")

    if gap.critical_gaps:
        print(f"\n  GAPS FOUND ({len(gap.critical_gaps)}):")
        for g in gap.critical_gaps:
            lvl = SEVERITY_COLOR.get(g.get("risk_level", "low"), "LOW")
            print(f"    [{lvl}] {g.get('gap_id', '?')} — {g.get('evasion_technique', '')}")
            print(f"      Root cause: {g.get('root_cause', '')[:100]}")
            fix = g.get("proposed_fix", {})
            if fix.get("regex"):
                print(f"      Fix: add pattern '{fix['pattern_name']}': {fix['regex'][:80]}")

    if gap.false_positive_issues:
        print(f"\n  FALSE POSITIVE ISSUES ({len(gap.false_positive_issues)}):")
        for fp in gap.false_positive_issues:
            print(f"    [{fp.get('triggered_pattern', '?')}] {fp.get('root_cause', '')[:80]}")

    if gap.testing_blind_spots:
        print(f"\n  TESTING BLIND SPOTS:")
        for bs in gap.testing_blind_spots:
            print(f"    • {bs}")

    if gap.recommended_actions:
        print(f"\n  RECOMMENDED ACTIONS:")
        for action in sorted(gap.recommended_actions, key=lambda a: a.get("priority", 99)):
            p = action.get("priority", "?")
            effort = action.get("effort", "?")
            print(f"    [{p}] [{effort.upper()}] {action.get('action', '')}")


def _save_markdown_report(gap: GapReport, exec_report: ExecutionReport, path: Path) -> None:
    s = exec_report.summary()
    icon = VERDICT_ICONS.get(gap.overall_verdict, "?")

    lines = [
        "# AgentWatch Testing Gap Report",
        f"*Generated by agentic tester — {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}*",
        "",
        f"## Overall Verdict: {icon} {gap.overall_verdict}",
        "",
        gap.summary,
        "",
        "## Detection Metrics",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Attacks tested | {s['attacks_tested']} |",
        f"| Detected | {s['attacks_detected']} ({s['detection_rate']:.0%}) |",
        f"| Missed | {s['attacks_missed']} |",
        f"| Benign tested | {s['benign_tested']} |",
        f"| False positives | {s['false_positives']} ({s['fp_rate']:.0%}) |",
        f"| Avg latency | {s['avg_latency_ms']:.1f}ms |",
        "",
    ]

    if gap.critical_gaps:
        lines += ["## Detection Gaps", ""]
        for g in gap.critical_gaps:
            lvl = g.get("risk_level", "low").upper()
            lines += [
                f"### [{lvl}] {g.get('gap_id', '?')} — {g.get('evasion_technique', '')}",
                "",
                f"**Root cause:** {g.get('root_cause', '')}",
                "",
                "**Missed payloads:**",
            ]
            for p in g.get("missed_payloads", []):
                lines.append(f"- `{p}`")
            fix = g.get("proposed_fix", {})
            if fix:
                lines += [
                    "",
                    f"**Proposed fix:** `{fix.get('pattern_name', '')}`",
                    f"```regex",
                    fix.get("regex", ""),
                    "```",
                    f"*{fix.get('rationale', '')}*",
                ]
            lines.append("")

    if gap.false_positive_issues:
        lines += ["## False Positive Issues", ""]
        for fp in gap.false_positive_issues:
            lines += [
                f"- **Pattern:** `{fp.get('triggered_pattern', '?')}` — {fp.get('root_cause', '')}",
                f"  Fix: {fp.get('proposed_fix', '')}",
            ]
        lines.append("")

    if gap.testing_blind_spots:
        lines += ["## Testing Blind Spots", ""]
        for bs in gap.testing_blind_spots:
            lines.append(f"- {bs}")
        lines.append("")

    if gap.recommended_actions:
        lines += ["## Recommended Actions", ""]
        lines += ["| Priority | Effort | Action |", "|----------|--------|--------|"]
        for action in sorted(gap.recommended_actions, key=lambda a: a.get("priority", 99)):
            lines.append(
                f"| {action.get('priority', '?')} | {action.get('effort', '?').upper()} "
                f"| {action.get('action', '')} |"
            )
        lines.append("")

    if exec_report.misses:
        lines += ["## Missed Attack Payloads (full list)", ""]
        for r in exec_report.misses:
            lines += [
                f"**Component:** {r.component}  ",
                f"**Payload:** `{r.payload}`  ",
                f"**Attack type:** {r.attack_type}  ",
                f"**Evasion:** {r.evasion_rationale}",
                "",
            ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"\n  Report saved → {path}")


async def run(
    verbose: bool = False,
    output_json: str | None = None,
    save_report: str | None = None,
) -> int:
    """Full orchestration flow. Returns exit code (0=pass, 1=gaps found, 2=error)."""

    print("AgentWatch Agentic Tester")
    print("=" * 60)
    print("  Agents: Recon → Planner → Executor → Analyst")
    print()

    # ── Phase 1: Recon ─────────────────────────────────────────────────────
    print("  Phase 1/4: ReconAgent — mapping detection surface...")
    surface = load_detection_surface()
    print(f"    Content patterns: {len(surface.content_patterns)}")
    print(f"    MIM patterns:     {len(surface.mim_regex_patterns)}")
    print(f"    SF thresholds:    {surface.silent_failure_thresholds}")

    # ── Phase 2: Plan ──────────────────────────────────────────────────────
    print("\n  Phase 2/4: PlannerAgent — generating adversarial payloads with Claude...")
    planner_out = run_planner(surface, verbose=verbose)

    if planner_out.error:
        print(f"  [ERROR] PlannerAgent failed: {planner_out.error}")
        return 2

    total_payloads = (
        len(planner_out.content_inspector_attacks)
        + len(planner_out.content_inspector_benign)
        + len(planner_out.mim_attacks)
        + len(planner_out.mim_benign)
    )
    print(f"    Generated {total_payloads} payloads:")
    print(f"      ContentInspector attacks: {len(planner_out.content_inspector_attacks)}")
    print(f"      ContentInspector benign:  {len(planner_out.content_inspector_benign)}")
    print(f"      MIM attacks:              {len(planner_out.mim_attacks)}")
    print(f"      MIM benign:               {len(planner_out.mim_benign)}")

    # ── Phase 3: Execute ───────────────────────────────────────────────────
    print(f"\n  Phase 3/4: ExecutorAgent — running {total_payloads} payloads through live code...")
    exec_report = await run_executor(planner_out, verbose=verbose)
    _print_exec_results(exec_report)

    # ── Phase 4: Analyze ───────────────────────────────────────────────────
    print("\n  Phase 4/4: AnalystAgent — synthesizing gaps with Claude...")
    gap_report = run_analyst(exec_report, verbose=verbose)

    if gap_report.error:
        print(f"  [ERROR] AnalystAgent failed: {gap_report.error}")
        # Still show raw results
        _print_exec_results(exec_report)
        return 2

    _print_gap_report(gap_report)

    # ── Output ─────────────────────────────────────────────────────────────
    if output_json:
        s = exec_report.summary()
        data = {
            "verdict": gap_report.overall_verdict,
            "summary": gap_report.summary,
            "metrics": s,
            "critical_gaps": gap_report.critical_gaps,
            "false_positive_issues": gap_report.false_positive_issues,
            "testing_blind_spots": gap_report.testing_blind_spots,
            "recommended_actions": gap_report.recommended_actions,
            "missed_payloads": [
                {"payload": r.payload, "component": r.component,
                 "attack_type": r.attack_type, "evasion": r.evasion_rationale}
                for r in exec_report.misses
            ],
            "false_positives": [
                {"payload": r.payload, "component": r.component,
                 "pattern": r.pattern_matched}
                for r in exec_report.false_positives
            ],
        }
        Path(output_json).parent.mkdir(parents=True, exist_ok=True)
        Path(output_json).write_text(json.dumps(data, indent=2))
        print(f"\n  JSON output saved → {output_json}")

    if save_report:
        _save_markdown_report(gap_report, exec_report, Path(save_report))

    print("\n" + "=" * 60)

    # Exit code based on gaps found
    s = exec_report.summary()
    if gap_report.overall_verdict == "CRITICAL" or s["attacks_missed"] > 0:
        return 1
    return 0
